### ISSUE TITLE
How to build a libaudiofile.so? possible?

### ISSUE THREAD

**Issue by JoshuaBatty** [mpruett/audiofile#23]
Hi I am trying to build audiofile so that I can use the now old Tao Physical Modelling synthesis library. Only problem is that Tao seems to want to find a libaudiofile.so in order to create a make file. 

I am running osx 10.10.1. I can only seem to be able to build .dylib and .a files for audiofile. Do you know how to build a .so file? Thanks.

**Comment by mpruett** [comment]
As I imagine you already figured out, on OS X, shared libraries have the file extension .dylib whereas on most other UNIX systems including Linux, shared libraries have the file extension .so.
