### ISSUE TITLE
bzero() in CAF.cpp

### ISSUE THREAD

**Issue by sorrge** [mpruett/audiofile#24]
In the CAF.cpp, the non-standard, deprecated bzero() function is used, which causes compilation problems. memset() is a better alternative.

**Comment by AntumDeluge** [comment]
How do I use *[memset][]* in place of *[bzero]*? Would it be:
* *memset(m_codecData->data(), 0, m_codecData->size())*

*bzero* writes zeros to memory, correct?

[memset]: http://linux.die.net/man/3/memset
[bzero]: http://linux.die.net/man/3/bzero

**Comment by AntumDeluge** [comment]
Here is a patch for replacing *bzero* with *memset*. Hope this is the right way to do it.
[audiofile-0.3.6-libaudiofile__CAF.cpp.patch.txt](https://github.com/mpruett/audiofile/files/46295/audiofile-0.3.6-libaudiofile__CAF.cpp.patch.txt)

**Comment by mpruett** [comment]
Thanks for noting this issue; it's resolved in d9363a5d16af4ce55eb35c5aad9ca19bb9c53cbe.
